{% set name = "pymov2gif" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymov2gif-{{ version }}.tar.gz
  sha256: c1177d15cec974996abb9ec97bdb6660e7dacc11cf96d2ace558f53a101ef789

build:
  entry_points:
    - pymov2gif=pymov2gif.__main__:command_line_parser
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - ffmpeg
    - gifsicle

test:
  imports:
    - pymov2gif
  commands:
    - pip check
    - pymov2gif --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyscioffice/pymov2gif
  summary: Similar to the Google authenticator just written in python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
