{% set name = "pymov2gif" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymov2gif-{{ version }}.tar.gz
  sha256: 7e483534a0ead72e7be5a8526a1295d0bc68fc9d799a0a8fefe472fd6a295346

build:
  entry_points:
    - pymov2gif=pymov2gif.__main__:command_line_parser
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ffmpeg
    - gifsicle

test:
  imports:
    - pymov2gif
  commands:
    - pip check
    - pymov2gif --help
  requires:
    - pip

about:
  home: https://github.com/pyscioffice/pymov2gif
  summary: Similar to the Google authenticator just written in python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
